TADS:
  RAW: "data/Dixon_2015_stability_formatted_TADs.bed"

ANNOTATIONS:
  GENES: "data/gnomad_genes_pli_loeuf_HI.bed"
  EXONS: "data/HAVANA_exon.merged.bed.gz"
  ENHANCERS: "data/fantom5_enhancer_phastcon_average.bed"
  CTCF: "data/H1_hESC_CTCF_peaks_idr_optimal.bed"
  DDG2P: "data/DDG2P_genes.bed"
  POINT: "data/extracted_po_pairs.bed"

CNVS:
  RAW:
  ANNOTATED:

FEATURES: "extended"

CLASSIFIER: "rf"

PRETRAINED_MODEL: "data/default_model.p"
